package it.unibo.geometrybash.model.collision;

/**
 * Defines the collision-handling capability of a game object.
 *
 * <p>
 * Implementing this interface allows an object to receive and process
 * collision events involving other game objects.
 * </p>
 */
@FunctionalInterface
public interface Collidable {

    /**
     * Processes a collision event involving this object.
     *
     * @param event the collision event generated by the collision system
     */
    void onCollision(CollisionEvent event);
}
