package it.unibo.geometrybash.commons.pattern.observerpattern.viewobserverpattern;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import it.unibo.geometrybash.commons.pattern.observerpattern.Event;

/**
 * A class that represent an event generated by the view that is listened by a view observer.
 *
 * <p>The event type is represented using {@link ViewEventType}.
 * 
 * @see ViewObserver
 * @see Event 
 */
public final class ViewEvent implements Event {

    /**
     * Logger useful for debug purposes.
     */
    private static final Logger LOGGER = LoggerFactory.getLogger(ViewEvent.class);

    /**
     * The type of event generated.
     * 
     * @see ViewEventType
     */
    private final ViewEventType type;

    private ViewEvent(final ViewEventType type) {
        this.type = type;
    }

    /**
     * A factory static method to create an event that represents the resume command is called in the view. 
     * 
     * @return a instance of this class with type  {@link ViewEventType#RESUME}.
     */
    public static ViewEvent createResumeEvent() {
        LOGGER.debug("Created a new ResumeEvent");
        return new ViewEvent(ViewEventType.RESUME);
    }

    /**
     * A method that returns the type of the event.
     * 
     * @return the {@link ViewEventType} of this instance.
     */
    public ViewEventType getType() {
        return type;
    }

    /**
     * A method that returns the name of the event.
     * 
     * @return the name of the type represented by this event.
     */
    @Override
    public String getEventName() {
        return type.getName();
    }
}
